// import './noiseLines'
// import './lines'
// import './streamlines'
// import './imagePainting'
// import './imagePainting2'
// import './imagePainting3'
// import './imagePainting4'
// import './colorsPainting'
import './noisePolygonTest'
// import './imagePaintingPixi'
// import './noiseLinesPixi'

// import './3d/cylinderTracks.js'
// import './3d/sphereSpline.js'